### PR TITLE
Update coin.tsx

### PR DESCRIPTION
**Pull request by wiee182**

### CODE REVIEW

**Review by FrassAsass — APPROVED** [review]

**Comment by FrassAsass** [comment]
Live. Please test before sharing.

**Comment by wiee182** [comment]
> Live. Please test before sharing.

sir the token amount is wrong

it's 21k not 1k

**Comment by FrassAsass** [comment]
fixed. Please check.

**Comment by wiee182** [comment]
> fixed. Please check.

$DE Token amount is wrong 
It should be 1k per 1 $DE NFT not 21k

**Comment by wiee182** [comment]
Screenshot 2024-02-10 083154

**Comment by FrassAsass** [comment]
Those numbers are the same in our app. One is a string, one is a number in the array. But they are the same number and have to do with tokens to nft. Can join discord and hit me up in real time :) Happy to fix, ensure we get it right.

**Pull request merged**
